---
vagrant_box: debian/stretch64
vagrant_user: vagrant
vagrant_hostname: curvation.dev
vagrant_machine_name: curvationvm
vagrant_synced_folders:
  - local_path: .
    destination: /vagrant
    type: nfs
    create: true
  - local_path: ./app/src
    destination: /var/www/curvation/src
    type: nfs
    create: true
  - local_path: ./app/logs
    destination: /var/www/curvation/logs
    type: nfs
    create: true
